#!/usr/bin/env python3
"""Add more new projects found from additional searches."""
import json

NEW_PROJECTS = [
    # From openclaw+esp32/arduino/seeed search
    {
        "name": "XiaohongshuSkills",
        "owner": "white0dew",
        "stars": 2313,
        "description": "支持小红书自动发布、自动评论、自动检索的 Skill。支持 OpenClaw、Codex、CC 等",
        "platforms": ["OpenClaw"],
        "category": "tool",
        "highlights": ["小红书自动发布", "自动评论", "自动检索"],
        "seeedstudio": False,
        "bom_cost": "Free",
    },
    {
        "name": "xiaohongshu-ops-skill",
        "owner": "Xiangyu-CAS",
        "stars": 1314,
        "description": "把Openclaw 变成小红书运营助手，帮你分析、选题、创作、复盘、复刻，甚至全面托管",
        "platforms": ["OpenClaw"],
        "category": "tool",
        "highlights": ["小红书运营助手", "选题创作", "自动托管"],
        "seeedstudio": False,
        "bom_cost": "Free",
    },
    {
        "name": "xiaohongshu-auto-operation",
        "owner": "ijerryhuang",
        "stars": 31,
        "description": "小红书账号全自动运营系统 - OpenClaw Skill",
        "platforms": ["OpenClaw"],
        "category": "tool",
        "highlights": ["小红书运营", "全自动"],
        "seeedstudio": False,
        "bom_cost": "Free",
    },
    {
        "name": "xiaohongshu-mcp-skill",
        "owner": "tclawde",
        "stars": 9,
        "description": "Xiaohongshu MCP skill for OpenClaw - Complete automation solution",
        "platforms": ["OpenClaw"],
        "category": "tool",
        "highlights": ["小红书MCP", "自动化"],
        "seeedstudio": False,
        "bom_cost": "Free",
    },
    {
        "name": "xiaohongshu-skill",
        "owner": "DeliciousBuding",
        "stars": 7,
        "description": "小红书Skill — 基于 Python Playwright 的搜索、帖子详情、用户主页提取工具",
        "platforms": ["OpenClaw"],
        "category": "tool",
        "highlights": ["小红书", "Playwright"],
        "seeedstudio": False,
        "bom_cost": "Free",
    },
    {
        "name": "pinclaw",
        "owner": "ericshang98",
        "stars": 104,
        "description": "The first hardware product built for OpenClaw. A wearable AI clip ecosystem — hardware, firmware, and plugin.",
        "platforms": ["Wearables"],
        "category": "iot",
        "highlights": ["可穿戴设备", "硬件产品", "固件"],
        "seeedstudio": False,
        "bom_cost": "~$30",
    },
    {
        "name": "clawstage",
        "owner": "HooRii-OT",
        "stars": 45,
        "description": "ClawStage is an open and modular hardware platform designed to allow OpenClaw to translate local intelligence into physical behavior. Acts as a tangible shell for a single, persistent AI identity — providing display, voice, sensors, and physical presence.",
        "platforms": ["ESP32", "Custom Hardware"],
        "category": "robotics",
        "highlights": ["模块化硬件平台", "物理交互", "传感器"],
        "seeedstudio": False,
        "bom_cost": "Varies",
    },
    {
        "name": "DuckyClaw",
        "owner": "tuya",
        "stars": 113,
        "description": "Edge-Hardware (SoC/MCU) oriented Claw🦞",
        "platforms": ["IoT", "SoC", "MCU"],
        "category": "iot",
        "highlights": ["边缘硬件", "SoC/MCU"],
        "seeedstudio": False,
        "bom_cost": "Varies",
    },
    {
        "name": "claw-spark",
        "owner": "saiyam1814",
        "stars": 9,
        "description": "One-click AI agent setup for NVIDIA DGX Spark, Jetson, and RTX hardware. OpenClaw + Ollama, fully local.",
        "platforms": ["NVIDIA Jetson", "DGX Spark", "RTX"],
        "category": "ai_compute",
        "highlights": ["NVIDIA DGX Spark", "Jeston", "本地部署"],
        "seeedstudio": False,
        "bom_cost": "Varies",
    },
    {
        "name": "openclaw-voice-client-s3-box-lite",
        "owner": "brooqs",
        "stars": 2,
        "description": "Lightweight ESP-IDF firmware client to connect ESP32-S3-BOX-Lite to OpenClaw voice assistant bridge over Wi-Fi. Streams microphone audio and decodes MP3 responses via I2S hardware pipeline.",
        "platforms": ["ESP32-S3-BOX-Lite"],
        "category": "iot",
        "highlights": ["ESP32-S3-BOX-Lite", "语音", "WiFi桥接"],
        "seeedstudio": False,
        "bom_cost": "~$25",
    },
    # From openclaw+voice/robot/hardware search
    {
        "name": "OpenClaw-Robotics",
        "owner": "LooperRobotics",
        "stars": 28,
        "description": "High-performance control stack for Embodied AI powered by the OpenClaw ecosystem. Designed for high-dynamic platforms including Humanoids and Quadrupeds, providing unified whole-body control (WBC) interfaces, sim-to-real pipelines, and low-latency hardware abstraction.",
        "platforms": ["Humanoids", "Quadrupeds", "Robotics"],
        "category": "robotics",
        "highlights": ["具身AI", "全身控制", "人形机器人"],
        "seeedstudio": False,
        "bom_cost": "Varies",
    },
    {
        "name": "claw-cash",
        "owner": "tiero",
        "stars": 29,
        "description": "Bitcoin wallet for AI agents. Stablecoins in, Bitcoin out. Keys in hardware enclaves. Works with OpenClaw, Claude Code, or any agent harness.",
        "platforms": ["PC"],
        "category": "tool",
        "highlights": ["比特币钱包", "硬件安全", "AI代理"],
        "seeedstudio": False,
        "bom_cost": "Free",
    },
    {
        "name": "lobster",
        "owner": "eternalai-org",
        "stars": 22,
        "description": "The Agentic Computer - AI agent operating system",
        "platforms": ["PC"],
        "category": "core",
        "highlights": ["Agentic Computer", "操作系统"],
        "seeedstudio": False,
        "bom_cost": "Free",
    },
    {
        "name": "zbot",
        "owner": "LingaoM",
        "stars": 15,
        "description": "zbot 🦞 - an embedded AI agent running on Zephyr RTOS across multiple hardware platforms.",
        "platforms": ["Zephyr RTOS"],
        "category": "iot",
        "highlights": ["Zephyr RTOS", "嵌入式AI"],
        "seeedstudio": False,
        "bom_cost": "~$15",
    },
    {
        "name": "openclaw-secure",
        "owner": "seomikewaltman",
        "stars": 11,
        "description": "Hardware-gated secret management for AI agents. Secures Clawdbot API keys with pluggable backends (Keychain, 1Password, Bitwarden, and more).",
        "platforms": ["PC", "Mac", "Linux"],
        "category": "tool",
        "highlights": ["密钥管理", "硬件安全", "1Password"],
        "seeedstudio": False,
        "bom_cost": "Free",
    },
    {
        "name": "openclaw-mobile",
        "owner": "howardleegeek",
        "stars": 4,
        "description": "ClawPhones — Multi-platform AI assistant for Oyster Labs hardware (Universal Phone, Puffy, ClawGlasses). Tiered LLM routing (DeepSeek/Kimi/Claude), conversation persistence.",
        "platforms": ["Mobile", "Wearables"],
        "category": "iot",
        "highlights": ["移动端", "多平台", "LLM路由"],
        "seeedstudio": False,
        "bom_cost": "Varies",
    },
    {
        "name": "rustclaw",
        "owner": "lucas-moraes",
        "stars": 7,
        "description": "Project to run some like openclaw in small hardwares. A 100% Rust remade alternative to OpenClaw that runs smoothly on low-cost hardware under $10.",
        "platforms": ["Embedded", "Rust"],
        "category": "core",
        "highlights": ["Rust重制", "低成本硬件", "$10以下"],
        "seeedstudio": False,
        "bom_cost": "~$10",
    },
    {
        "name": "AirClaw",
        "owner": "miga1999",
        "stars": 3,
        "description": "Run OpenClaw locally on any GPU or CPU without API costs, supporting large models on low-memory hardware for free and offline use.",
        "platforms": ["PC", "GPU", "CPU"],
        "category": "core",
        "highlights": ["本地运行", "无API成本", "低显存"],
        "seeedstudio": False,
        "bom_cost": "Free",
    },
    {
        "name": "awesome-openclaw-hardware-projects",
        "owner": "Seeed-Projects",
        "stars": 13,
        "description": "Collection of awesome openclaw hardware projects",
        "platforms": ["Seeed Studio", "ESP32", "XIAO"],
        "category": "maker",
        "highlights": ["Seeed硬件项目集合"],
        "seeedstudio": True,
        "bom_cost": "Free",
    },
    {
        "name": "nanoclaw",
        "owner": "qwibitai",
        "stars": 26038,
        "description": "A lightweight alternative to OpenClaw that runs in containers for security. Connects to WhatsApp, Telegram, Slack, Discord, Gmail and other messaging apps, has memory, scheduled jobs, and runs directly on Anthropic's Agents SDK.",
        "platforms": ["PC", "Mac", "Linux", "Docker"],
        "category": "core",
        "highlights": ["轻量级替代", "容器化", "多平台集成"],
        "seeedstudio": False,
        "bom_cost": "Free",
    },
    {
        "name": "OpenViking",
        "owner": "volcengine",
        "stars": 20166,
        "description": "Open-source context database designed specifically for AI Agents(such as openclaw). Unifies management of context (memory, resources, and skills) through a file system paradigm, enabling hierarchical context delivery and self-evolving.",
        "platforms": ["PC", "Mac", "Linux"],
        "category": "tool",
        "highlights": ["上下文数据库", "记忆管理", "自进化"],
        "seeedstudio": False,
        "bom_cost": "Free",
    },
    {
        "name": "edict",
        "owner": "cft0808",
        "stars": 13690,
        "description": "🏛️ 三省六部制 · OpenClaw Multi-Agent Orchestration System — 9 specialized AI agents with real-time dashboard, model config, and full audit trails",
        "platforms": ["PC", "Mac", "Linux"],
        "category": "tool",
        "highlights": ["多智能体编排", "实时仪表板", "审计追踪"],
        "seeedstudio": False,
        "bom_cost": "Free",
    },
    {
        "name": "memU",
        "owner": "NevaMind-AI",
        "stars": 13248,
        "description": "Memory for 24/7 proactive agents like openclaw (moltbot, clawdbot).",
        "platforms": ["PC", "Mac", "Linux"],
        "category": "tool",
        "highlights": ["长期记忆", "24/7代理"],
        "seeedstudio": False,
        "bom_cost": "Free",
    },
    {
        "name": "MemOS",
        "owner": "MemTensor",
        "stars": 7994,
        "description": "AI memory OS for LLM and Agent systems(moltbot,clawdbot,openclaw), enabling persistent Skill memory for cross-task skill reuse and evolution.",
        "platforms": ["PC", "Mac", "Linux"],
        "category": "tool",
        "highlights": ["记忆操作系统", "跨任务技能复用"],
        "seeedstudio": False,
        "bom_cost": "Free",
    },
    {
        "name": "ClawRouter",
        "owner": "BlockRunAI",
        "stars": 6530,
        "description": "The agent-native LLM router for OpenClaw. 41+ models, <1ms routing, USDC payments on Base & Solana via x402.",
        "platforms": ["PC", "Mac", "Linux"],
        "category": "tool",
        "highlights": ["LLM路由", "41+模型", "USDC支付"],
        "seeedstudio": False,
        "bom_cost": "Free",
    },
    {
        "name": "Star-Office-UI",
        "owner": "ringhyacinth",
        "stars": 6362,
        "description": "A pixel office for your OpenClaw: turn invisible work states into a cozy little space with characters, daily notes, and guest agents. Code under MIT; art assets for non-commercial learning only.",
        "platforms": ["PC"],
        "category": "tool",
        "highlights": ["像素办公室", "多智能体协作"],
        "seeedstudio": False,
        "bom_cost": "Free",
    },
    {
        "name": "FlyEnv",
        "owner": "xpf0000",
        "stars": 2648,
        "description": "Lightweight Native Local Dev Toolbox for Windows, macOS & Linux. Run OpenClaw/n8n/Apache/Nginx/Caddy/Tomcat/PHP/Node.js/Bun/Deno/Python/Java/Go/Ruby/Perl/Rust/Erlang/MySQL/PostgreSQL/MariaDB/MongoDB/Redis/RabbitMQ without Docker.",
        "platforms": ["PC", "Mac", "Linux"],
        "category": "tool",
        "highlights": ["本地开发环境", "无Docker"],
        "seeedstudio": False,
        "bom_cost": "Free",
    },
    {
        "name": "openclaw-memory-openviking",
        "owner": "clawd20130",
        "stars": 4,
        "description": "OpenViking context database as memory backend for OpenClaw",
        "platforms": ["PC"],
        "category": "tool",
        "highlights": ["OpenViking集成", "记忆后端"],
        "seeedstudio": False,
        "bom_cost": "Free",
    },
    {
        "name": "openclaw-notion-sync",
        "owner": "321559841",
        "stars": 4,
        "description": "Sync OpenClaw agent configuration to Notion databases",
        "platforms": ["PC"],
        "category": "tool",
        "highlights": ["Notion同步"],
        "seeedstudio": False,
        "bom_cost": "Free",
    },
    {
        "name": "openclaw-dashboard",
        "owner": "anis-marrouchi",
        "stars": 2,
        "description": "A lightweight, single-file OpenClaw dashboard for real-time agent fleet monitoring — no build step, no database, no Docker.",
        "platforms": ["PC"],
        "category": "tool",
        "highlights": ["轻量级仪表板", "舰队监控"],
        "seeedstudio": False,
        "bom_cost": "Free",
    },
    {
        "name": "xiaohongshu",
        "owner": "Youhai020616",
        "stars": 11,
        "description": "AI-powered Xiaohongshu (小红书/RED) automation — publish, search, engage, analyze. MCP + CDP.",
        "platforms": ["OpenClaw"],
        "category": "tool",
        "highlights": ["小红书自动化", "MCP+CDP"],
        "seeedstudio": False,
        "bom_cost": "Free",
    },
    {
        "name": "openclaw-xiaohongshu",
        "owner": "jiangguishan",
        "stars": 10,
        "description": "openclaw小红书插件",
        "platforms": ["OpenClaw"],
        "category": "tool",
        "highlights": ["小红书插件"],
        "seeedstudio": False,
        "bom_cost": "Free",
    },
    {
        "name": "xiaohongshu-skill",
        "owner": "aaa17001",
        "stars": 2,
        "description": "OpenClaw 小红书自动发布技能 - 完整自动化流程：内容生成 → 新闻收集 → 文案编写 → 自动发布",
        "platforms": ["OpenClaw"],
        "category": "tool",
        "highlights": ["小红书自动发布"],
        "seeedstudio": False,
        "bom_cost": "Free",
    },
    {
        "name": "xiaohongshu-publish-skill",
        "owner": "zangqilong198812",
        "stars": 5,
        "description": "RedNote publish skill for openclaw. User Chrome to publish RedNote post.",
        "platforms": ["OpenClaw"],
        "category": "tool",
        "highlights": ["RedNote发布"],
        "seeedstudio": False,
        "bom_cost": "Free",
    },
    {
        "name": "neuralbridge",
        "owner": "iceccarelli",
        "stars": 1,
        "description": "Open-source middleware that lets any AI agent (OpenClaw, LangChain, AutoGPT) securely connect to any API, database, or enterprise system via YAML config. Features 22+ adapters, zero-trust security, EU CRA compliance engine, MCP gateway, React dashboard, and OpenClaw plugin support.",
        "platforms": ["PC", "Mac", "Linux"],
        "category": "tool",
        "highlights": ["API中间件", "企业系统集成", "MCP网关"],
        "seeedstudio": False,
        "bom_cost": "Free",
    },
]

with open("data/projects.json") as f:
    projects = json.load(f)

existing_urls = {p["github_url"] for p in projects}

added = 0
for np in NEW_PROJECTS:
    url = f"https://github.com/{np['owner']}/{np['name']}"
    if url not in existing_urls:
        new_entry = {
            "id": len(projects) + 1,
            "name": np["name"],
            "stars": np["stars"],
            "category": np["category"],
            "platforms": np["platforms"],
            "description": np["description"],
            "highlights": np["highlights"],
            "github_url": url,
            "seeedstudio": np["seeedstudio"],
            "product_links": [],
            "bom_cost": np["bom_cost"],
            "daily_increment": 0,
            "created_at": "2026-03-31T00:00:00Z",
        }
        projects.append(new_entry)
        existing_urls.add(url)
        added += 1
        print(f"  + {np['owner']}/{np['name']} ({np['stars']} stars)")

print(f"\nAdded {added} new projects. Total: {len(projects)}")

with open("data/projects.json", "w") as f:
    json.dump(projects, f, indent=2, ensure_ascii=False)

print("Saved data/projects.json")